TEST_CARD_DATA = {
    "Amount": 10,
    "Currency": "RUB",
    "InvoiceId": "1234567",
    "IpAddress": "123.123.123.123",
    "Description": "Оплата товаров в example.com",
    "AccountId": "user_x",
    "Name": "CARDHOLDER NAME",
    "CardCryptogramPacket": "01492500008719030128SMfLeYdKp5dSQVIiO5l6ZCJiPdel4uDjdFTTz1UnXY+3QaZcNOW8lmXg0H670MclS4lI+qLkujKF4pR5Ri+T/E04Ufq3t5ntMUVLuZ998DLm+OVHV7FxIGR7snckpg47A73v7/y88Q5dxxvVZtDVi0qCcJAiZrgKLyLCqypnMfhjsgCEPF6d4OMzkgNQiynZvKysI2q+xc9cL0+CMmQTUPytnxX52k9qLNZ55cnE8kuLvqSK+TOG7Fz03moGcVvbb9XTg1oTDL4pl9rgkG3XvvTJOwol3JDxL1i6x+VpaRxpLJg0Zd9/9xRJOBMGmwAxo8/xyvGuAj85sxLJL6fA==",
    "Payer":
        {
            "FirstName": "Тест",
            "LastName": "Тестов",
            "MiddleName": "Тестович",
            "Birth": "1955-02-24",
            "Address": "тестовый проезд дом тест",
            "Street": "Lenina",
            "City": "MO",
            "Country": "RU",
            "Phone": "123",
            "Postcode": "345"
        }
}

TEST_TOKEN_DATA = {
    "Amount": 59,
    "Currency": "RUB",
    "InvoiceId": "1234567",
    "Description": "Оплата товаров в example.com",
    "AccountId": "user_x",
    "Token": "success_1111a3e0-2428-48fb-a530-12815d90d0e8"
}

TEST_HEADER = {
    "Authorization": "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
}

SUCCESS_CARD_PAYMENT_RESPONSE = {
    "Model": {
        "ReasonCode": 0,
        "PublicId": "pk_********************************",
        "TerminalUrl": "http://test.test",
        "TransactionId": 891510444,
        "Amount": 10,
        "Currency": "RUB",
        "CurrencyCode": 0,
        "PaymentAmount": 10,
        "PaymentCurrency": "RUB",
        "PaymentCurrencyCode": 0,
        "InvoiceId": "1234567",
        "AccountId": "user_x",
        "Email": None,
        "Description": "Оплата товаров в example.com",
        "JsonData": None,
        "CreatedDate": "/Date(1635150224630)/",
        "PayoutDate": None,
        "PayoutDateIso": None,
        "PayoutAmount": None,
        "CreatedDateIso": "2021-10-25T08:23:44",
        "AuthDate": "/Date(1635150224739)/",
        "AuthDateIso": "2021-10-25T08:23:44",
        "ConfirmDate": None,
        "ConfirmDateIso": None,
        "AuthCode": "A1B2C3",
        "TestMode": True,
        "Rrn": None,
        "OriginalTransactionId": None,
        "FallBackScenarioDeclinedTransactionId": None,
        "IpAddress": "123.123.123.123",
        "IpCountry": "CN",
        "IpCity": "Beijing",
        "IpRegion": "Beijing",
        "IpDistrict": "Beijing",
        "IpLatitude": 39.9289,
        "IpLongitude": 116.3883,
        "CardFirstSix": "411111",
        "CardLastFour": "1111",
        "CardExpDate": "11/25",
        "CardType": "Visa",
        "CardProduct": "C",
        "CardCategory": "Visa Signature (Signature)",
        "EscrowAccumulationId": None,
        "IssuerBankCountry": "RU",
        "Issuer": "CloudPayments",
        "CardTypeCode": 0,
        "Status": "Authorized",
        "StatusCode": 2,
        "CultureName": "ru",
        "Reason": "Approved",
        "CardHolderMessage": "Оплата успешно проведена",
        "Type": 0,
        "Refunded": False,
        "Name": "CARDHOLDER NAME",
        "Token": "0a0afb77-8f41-4de2-9524-1057f9695303",
        "SubscriptionId": None,
        "GatewayName": "Test",
        "ApplePay": False,
        "AndroidPay": False,
        "WalletType": "",
        "TotalFee": 0
    },
    "Success": True,
    "Message": None
}

SUCCESS_TOKEN_PAYMENT_RESPONSE = {
    "Model": {
        "ReasonCode": 0,
        "PublicId": "pk_**************************",
        "TerminalUrl": "http://test.test",
        "TransactionId": 897728064,
        "Amount": 59,
        "Currency": "RUB",
        "CurrencyCode": 0,
        "PaymentAmount": 59,
        "PaymentCurrency": "RUB",
        "PaymentCurrencyCode": 0,
        "InvoiceId": 1234567,
        "AccountId": "user_x",
        "Email": None,
        "Description": "Оплата товаров в example.com",
        "JsonData": None,
        "CreatedDate": "/Date(1635562705992)/",
        "PayoutDate": None,
        "PayoutDateIso": None,
        "PayoutAmount": None,
        "CreatedDateIso": "2021-10-30T02:58:25",
        "AuthDate": "/Date(1635562706070)/",
        "AuthDateIso": "2021-10-30T02:58:26",
        "ConfirmDate": "/Date(1635562706070)/",
        "ConfirmDateIso": "2021-10-30T02:58:26",
        "AuthCode": "A1B2C3",
        "TestMode": True,
        "Rrn": None,
        "OriginalTransactionId": None,
        "FallBackScenarioDeclinedTransactionId": None,
        "IpAddress": "87.251.91.164",
        "IpCountry": "RU",
        "IpCity": "Новосибирск",
        "IpRegion": "Новосибирская область",
        "IpDistrict": "Сибирский федеральный округ",
        "IpLatitude": 55.03923,
        "IpLongitude": 82.927818,
        "CardFirstSix": "424242",
        "CardLastFour": "4242",
        "CardExpDate": "12/25",
        "CardType": "Visa",
        "CardProduct": "I",
        "CardCategory": "Visa Infinite Infinite",
        "EscrowAccumulationId": None,
        "IssuerBankCountry": "RU",
        "Issuer": "CloudPayments",
        "CardTypeCode": 0,
        "Status": "Completed",
        "StatusCode": 3,
        "CultureName": "ru-RU",
        "Reason": "Approved",
        "CardHolderMessage": "Оплата успешно проведена",
        "Type": 0,
        "Refunded": False,
        "Name": "SER",
        "Token": "success_1111a3e0-2428-48fb-a530-12815d90d0e8",
        "SubscriptionId": None,
        "GatewayName": "Test",
        "ApplePay": False,
        "AndroidPay": False,
        "WalletType": "",
        "TotalFee": 0
    },
    "Success": True,
    "Message": None
}
